In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('DATASETS/ResultadosElectorales_2023_Generales.csv')

C:\Users\AlEx\AppData\Local\Temp\ipykernel_3076\441094444.py:1: DtypeWarning: Columns (7,10,11,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('DATASETS/ResultadosElectorales_2023_Generales.csv')

In [12]:
df.head()

,año,eleccion_tipo,recuento_tipo,padron_tipo,distrito_id,distrito_nombre,seccionprovincial_id,seccionprovincial_nombre,seccion_id,seccion_nombre,...,mesa_tipo,mesa_electores,cargo_id,cargo_nombre,agrupacion_id,agrupacion_nombre,lista_numero,lista_nombre,votos_tipo,votos_cantidad
0,2023,GENERAL,PROVISORIO,NORMAL,1,Ciudad Autónoma de Buenos Aires,0,NaN,1,Comuna 01,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,NULO,0
1,2023,GENERAL,PROVISORIO,NORMAL,1,Ciudad Autónoma de Buenos Aires,0,NaN,1,Comuna 01,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,IMPUGNADO,0
2,2023,GENERAL,PROVISORIO,NORMAL,1,Ciudad Autónoma de Buenos Aires,0,NaN,1,Comuna 01,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,RECURRIDO,0
3,2023,GENERAL,PROVISORIO,NORMAL,1,Ciudad Autónoma de Buenos Aires,0,NaN,1,Comuna 01,...,NATIVOS,343,1,PRESIDENTE Y VICE,0,NaN,0.0,NaN,COMANDO,0
4,2023,GENERAL,PROVISORIO,NORMAL,1,Ciudad Autónoma de Buenos Aires,0,NaN,1,Comuna 01,...,NATIVOS,349,1,PRESIDENTE Y VICE,134,UNION POR LA PATRIA,NaN,NaN,POSITIVO,95

In [17]:
df=df.drop(['lista_numero', 'lista_nombre', 'recuento_tipo', 'padron_tipo', 'eleccion_tipo', 'cargo_id', 'lista_numero', 'lista_nombre','seccionprovincial_id','seccion_nombre','seccionprovincial_nombre','año','seccion_id','circuito_id','circuito_nombre','mesa_tipo'], axis=1)

In [18]:
df = df.drop(df[df['cargo_nombre'] != 'PRESIDENTE Y VICE'].index) #elimino las filas donde el cargo que se vota no es presidente y vice

In [19]:
df.head()

,distrito_id,distrito_nombre,mesa_id,mesa_electores,cargo_nombre,agrupacion_id,agrupacion_nombre,votos_tipo,votos_cantidad
0,1,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,NULO,0
1,1,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,IMPUGNADO,0
2,1,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,RECURRIDO,0
3,1,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,COMANDO,0
4,1,Ciudad Autónoma de Buenos Aires,475,349,PRESIDENTE Y VICE,134,UNION POR LA PATRIA,POSITIVO,95

In [20]:
df['distrito_nombre'].unique() #veo como están escritos lod nombres de cada provincia y región

array(['Ciudad Autónoma de Buenos Aires', 'Buenos Aires', 'Catamarca',
       'Córdoba', 'La Pampa', 'Mendoza', 'Entre Ríos', 'Corrientes',
       'Río Negro', 'Neuquén', 'Salta', 'Santiago del Estero', 'Santa Fe',
       'Misiones', 'La Rioja', 'Chaco', 'Formosa', 'Chubut', 'Jujuy',
       'San Juan', 'Tucumán', 'San Luis',
       'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
       'Santa Cruz'], dtype=object)

In [22]:
def codigo_provincia(valor):
        if valor == 'Ciudad Autónoma de Buenos Aires':
           return 'AR-C'
        elif valor == 'Buenos Aires':
            return 'AR-B'
        elif valor == 'Catamarca':
            return 'AR-K'
        elif valor == 'Neuquén':
            return 'AR-Q'
        elif valor == 'San Luis':
            return 'AR-D'
        elif valor == 'Córdoba':
            return 'AR-X'
        elif valor == 'La Pampa':
            return 'AR-L'
        elif valor == 'Mendoza':
            return 'AR-M'
        elif valor == 'Entre Ríos':
            return 'AR-E'
        elif valor == 'Corrientes':
            return 'AR-W'
        elif valor == 'Río Negro':
            return 'AR-R'
        elif valor == 'Salta':
            return 'AR-A'
        elif valor == 'Santiago del Estero':
            return 'AR-G'
        elif valor == 'Santa Fe':
            return 'AR-S'
        elif valor == 'Misiones':
            return 'AR-N'
        elif valor == 'La Rioja':
            return 'AR-F'
        elif valor == 'Chaco':
            return 'AR-H'
        elif valor == 'Formosa':
            return 'AR-P'
        elif valor == 'Chubut':
            return 'AR-U'
        elif valor == 'Jujuy':
            return 'AR-Y'
        elif valor == 'San Juan':
            return 'AR-J'
        elif valor == 'Tucumán':
            return 'AR-T'
        elif valor == 'Tierra del Fuego':
            return 'AR-V'
        elif valor == 'Santa Cruz':
            return 'AR-Z'

In [23]:
df["distrito_id"] = df["distrito_nombre"].apply(lambda x: codigo_provincia(x)) #defino una función que genera una columna con el id correspondiente al mapa svg con el que voy a hacer el mapa coroplético

In [24]:
df.head()

,distrito_id,distrito_nombre,mesa_id,mesa_electores,cargo_nombre,agrupacion_id,agrupacion_nombre,votos_tipo,votos_cantidad
0,AR-C,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,NULO,0
1,AR-C,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,IMPUGNADO,0
2,AR-C,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,RECURRIDO,0
3,AR-C,Ciudad Autónoma de Buenos Aires,474,343,PRESIDENTE Y VICE,0,NaN,COMANDO,0
4,AR-C,Ciudad Autónoma de Buenos Aires,475,349,PRESIDENTE Y VICE,134,UNION POR LA PATRIA,POSITIVO,95

In [25]:
df.drop(['mesa_id','agrupacion_id', 'cargo_nombre'], axis=1, inplace=True)

In [28]:
df.head()

,distrito_id,distrito_nombre,mesa_electores,agrupacion_nombre,votos_tipo,votos_cantidad
0,AR-C,Ciudad Autónoma de Buenos Aires,343,NaN,NULO,0
1,AR-C,Ciudad Autónoma de Buenos Aires,343,NaN,IMPUGNADO,0
2,AR-C,Ciudad Autónoma de Buenos Aires,343,NaN,RECURRIDO,0
3,AR-C,Ciudad Autónoma de Buenos Aires,343,NaN,COMANDO,0
4,AR-C,Ciudad Autónoma de Buenos Aires,349,UNION POR LA PATRIA,POSITIVO,95

In [29]:
df.to_csv('DATASETS/Resultados_Generales_2023.csv', index=False)

In [5]:
len(df) #count number of rows in df

5868102

In [6]:
len(df.drop_duplicates()) #if there is a duplicated row in df, len must be diferent, but this is not the case

5868102

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5868102 entries, 0 to 5868101
Data columns (total 23 columns):
 #   Column                    Dtype
---  ------                    -----
 0   año                       int64
 1   eleccion_tipo             object
 2   recuento_tipo             object
 3   padron_tipo               object
 4   distrito_id               int64
 5   distrito_nombre           object
 6   seccionprovincial_id      int64
 7   seccionprovincial_nombre  object
 8   seccion_id                int64
 9   seccion_nombre            object
 10  circuito_id               object
 11  circuito_nombre           object
 12  mesa_id                   int64
 13  mesa_tipo                 object
 14  mesa_electores            int64
 15  cargo_id                  int64
 16  cargo_nombre              object
 17  agrupacion_id             int64
 18  agrupacion_nombre         object
 19  lista_numero              float64
 20  lista_nombre              object
 21  votos_tipo                object
 22  votos_cantidad            int64
dtypes: float64(1), int64(9), object(13)
memory usage: 1.0+ GB